# Copyright 2022 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Makefile for in-tree functions.

# Build all in-tree functions locally if function name not provided
# Otherwise, just build that function locally.
build-local:
	./scripts/build-local.sh $(FUNCTION_NAME)

# Run all unit tests for in-tree functions
unit-test:
	./scripts/unit-test.sh
